### ISSUE TITLE
Some profile links are not opened

### ISSUE THREAD

**Issue by andreiborisov** [robmathers/tweetbotlinks#3]
Some profile links are not opened in Tweetbot for some reason, it maybe some quirks with new Tweetbot 3.0 or maybe I've just noticed it.

Try the following Google search query and proceed to the user profile page (should be the first link in search results):

https://www.google.com/search?q=turbojedi+twitter

macOS 10.13.4, Safari 11.1, Tweetbot 3.0, Open in Tweetbot 1.0.1

**Comment by robmathers** [comment]
I haven't yet had a chance to test it out on Tweetbot 3 for Mac. It's possible the URL scheme has changed, or Twitter's URL structure changed (they do this occasionally). This project isn't high on my priority list at the moment, but I'll leave the issue open, and will look into it if I get a chance.
